# Generated by Django 3.0.5 on 2020-04-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=50)),
                ('bio', models.TextField()),
                ('task_name', models.CharField(max_length=50)),
                ('task_desc', models.TextField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('completed', models.BooleanField(default=False)),
                ('image', models.ImageField(default='Images/None/noimg.jpg', upload_to='Images/')),
            ],
        ),
    ]
